version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: TutorDb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"